name: Refresh lesson JSON

on:
  schedule:
  - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Cache output
      uses: actions/cache@v3
      with:
        path: out
        key: timetable-out
    - name: Generate JSON
      run: |
        python populate_lesson_json.py
    - name: Commit calendars
      run: |
        git config --global user.name 'Alessandro Benetton - Actions'
        git config --global user.email 'aleben98@gmail.com'
        git add -f out/* README.md
        git commit -am "Update lesson JSON list"
        git push
